# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/DigMe/Oscilloscope/project/Oscilloscope.srcs/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_auto_pc_0/oscilloscope_bd_auto_pc_0.xci
# IP: The module: 'oscilloscope_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/DigMe/Oscilloscope/project/Oscilloscope.gen/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_auto_pc_0/oscilloscope_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oscilloscope_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: u:/DigMe/Oscilloscope/project/Oscilloscope.srcs/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_auto_pc_0/oscilloscope_bd_auto_pc_0.xci
# IP: The module: 'oscilloscope_bd_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/DigMe/Oscilloscope/project/Oscilloscope.gen/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_auto_pc_0/oscilloscope_bd_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oscilloscope_bd_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
