# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/DigMe/Oscilloscope/project/Oscilloscope.srcs/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_processing_system7_0_1/oscilloscope_bd_processing_system7_0_1.xci
# IP: The module: 'oscilloscope_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/DigMe/Oscilloscope/project/Oscilloscope.gen/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_processing_system7_0_1/oscilloscope_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'oscilloscope_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: U:/DigMe/Oscilloscope/project/Oscilloscope.srcs/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_processing_system7_0_1/oscilloscope_bd_processing_system7_0_1.xci
# IP: The module: 'oscilloscope_bd_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/DigMe/Oscilloscope/project/Oscilloscope.gen/sources_1/bd/oscilloscope_bd/ip/oscilloscope_bd_processing_system7_0_1/oscilloscope_bd_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'oscilloscope_bd_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
